
from os import fchdir
from user import User
from credentials import Credentials
from click import confirm


def main():
    print("Hello Welcome to your pasword locker.")
    print('\n')
    print('Creat an account to store all your passwords safe and in one place')
    print('\n')
    proceed =confirm('continue?')
    if proceed:
       
        user_name = input('Enter the username: ')
        myPassword = input("password: ")
        confirm_password = input("Confirm password: ")
       
        if myPassword != confirm_password:
             print("Password does not match")
             while myPassword != confirm_password:
                 myPassword = input("password: ")
                 confirm_password = input("Confirm password: ")

        print('\n')        
        print(f"{user_name} you have been loged in successfully!")
        new_user = User(user_name, myPassword)
        print(len(User.user_login_information))
        User.saveLoginInfo(new_user)
        
        print('\n')
        print(f"Hello {user_name}, what would you like to do?")
        print('\n')

        while True:
                print("Use these short codes : cc - create a new account credentials, dc - display all account credentials, fc -find a contact, del - to delete an account, ex -exit the contact list ")

                short_code = input().lower()

                if short_code == 'cc':
                       
                        print ("Account name ....")
                        name = input()

                        print("username ...")
                        username = input()

                        confirm_generatePassword = confirm('Do you want autogenerated password: ')
                        if confirm_generatePassword:
                            password =Credentials.passwordGenerator()
                        else:
                            print("Password ...")
                            password = input()

                        new_account = Credentials(name, username, password)
                        Credentials.saveAccount(new_account) # create and save new account.
                        print ('\n')
                        print(f"New Account credentials {user_name} {password} for {name} account created")
                        print ('\n')

                elif short_code == 'dc':

                        if Credentials.displayAccounts():
                                print("Here is a list of all your accounts credentials")
                                print('\n')

                                for account in Credentials.displayAccounts():
                                        print(f"account name: {account.accountName}     username: {account.userName} password: {account.password}")

                                print('\n')
                        else:
                                print('\n')
                                print("You dont seem to have any contacts saved yet")
                                print('\n')

                elif short_code == 'fc':

                        search_account = input('enter the account name to search: ')
                        for account in Credentials.accountsCredentials:
                            if account.accountName == search_account:
                                print('\n')
                                print(f'Account name: {account.accountName}')
                                print(f"username: {account.userName}")
                                print(f'password: {account.password}')
                       
                        print('\n')

                elif short_code == 'del':

                        try:
                            
                            print("Enter the account name you want to delete")
                            toDelete = input("Name: ")

                            for account in Credentials.accountsCredentials:
                             if account.accountName == toDelete:
                                 confirm_delete = confirm(f'do you really want to delete {account.accountName} username: {account.userName}  password:{account.password}')
                                 if confirm_delete:
                                     Credentials.deleteAccount(account)
                                     print('\n')
                                     print('Account deleted successfully')
                                     print('\n')
                                 else:
                                     break
                        except:
                            print('The account does not exist')
                            print('\n')
                        

                elif short_code == "ex":
                        print("Bye .......")
                        break
                else:
                        print("I really didn't get that. Please use the short codes")
                        print('\n')

if __name__ == '__main__': 
    main()